### ISSUE TITLE
关于存储帧信息的图片, 存储 和 取出数字的疑问

### ISSUE THREAD

**Issue by platefaces** [zouchunyi/EmojiText#11]
```
       string t = System.Convert.ToString (zhen - 1, 2);            //sourceDic [key] 帧数
                float r = 0, g = 0, b = 0;
				if (t.Length >= 3) {
					r = t [2] == '1' ? 0.5f : 0;
					g = t [1] == '1' ? 0.5f : 0;
					b = t [0] == '1' ? 0.5f : 0;
				} else if (t.Length >= 2) {
					r = t [1] == '1' ? 0.5f : 0;
					g = t [0] == '1' ? 0.5f : 0;
				} else {
					r = t [0] == '1' ? 0.5f : 0;
				}
```
Shader中是这样取出来的
half frameCount = 1 + sign(data.r) + sign(data.g) * 2 + sign(data.b) * 4;    //二进制转换十进制

-----------------------------------------------------------------------------------------
我尝试以下修改
//EmojiBuild
float zhenf = zhen / 10f;
dataTex.SetPixel(x / EmojiSize, y / EmojiSize, new Color(zhenf, zhenf, zhenf, 1));

//Shader
half frameCount = data.r * 10 - 1;

是因为在shader无法判断data.r 是几位小数吗, 按照二进制的方式来存储
0.9    应该乘以10
0.12  应该乘以100
-----------------------------------------------------------------------------------------
2.  图片最多支持8 帧动画

**Comment by zouchunyi** [comment]
因为不同gpu在处理浮点运算会有差异
