### ISSUE TITLE
这个使用<color>这种的富文本不行啊。。。。谁会搞麻烦搞下吧

### ISSUE THREAD

**Issue by souba2012** [zouchunyi/EmojiText#15]
这个使用<color>这种的富文本不行啊，表情不显示了 显示%%。。。。谁会搞麻烦搞下吧

**Comment by souba2012** [comment]
看了下 应该是计算表情的位置错了 我自己改了下 把富文本的标签过滤掉就好了

**Comment by Wecica** [comment]
@souba2012 请教如何修改的
