### ISSUE TITLE
Text rect size

### ISSUE THREAD

**Issue by HassanAliAnjum** [zouchunyi/EmojiText#2]
right now key lenght is 3 **[0]** if we add more images and rebuild emojis it will increase like 4 **[1A]**. this effects text rect size
<img width="705" alt="screen shot 2016-12-28 at 5 23 59 pm" src="https://cloud.githubusercontent.com/assets/2786358/21522071/4914dc78-cd24-11e6-82b6-0229056f483e.png">

is there any way to fix it

**Comment by zouchunyi** [comment]
Actually there is no perfect solution to fix it. I use [0] as the size of every emoji,  that means [1] [11] or [11A] have the equal size. So the size of [1A][0][1B] is [0][0][0], and the extra width you see in the label cause of indent left.

**Comment by zouchunyi** [comment]
I ever used another solution that do not indent left, but it looked a little strange. if you wanna see, you can checkout to f49d9f93cc98ebfab29535e09de172c5136d2f32
