### ISSUE TITLE
表情换行bug2

### ISSUE THREAD

**Issue by cexlearning** [zouchunyi/EmojiText#4]
在表情换行后需要重置repairDistance = 0
![error2](https://cloud.githubusercontent.com/assets/22276189/22815999/2122793a-ef9a-11e6-84f6-51ca20dcc959.png)

如下代码可能会有帮助：
`for (int i = 0; i < vertCount; ++i) 
{
         if ((i - 4) >= 0 && verts[i - 4].position.y != verts[i].position.y)
        {
                //a new line need reset repairDistance
                repairDistance = 0;
        }
}`

**Comment by cexlearning** [comment]
补充new line 判断
if ( i % 4 == 0 && (i - 8) >= 0 && Mathf.Abs(verts[i - 8].position.y - verts[i].position.y) >= cachedTextGenerator.fontSizeUsedForBestFit){

**Comment by cexlearning** [comment]
或者修改老的换行判断
if (verts [i].position.y <= repairY)

**Comment by cexlearning** [comment]
因为新行的顶与上一行的底值有可能一样导致老的判断失效
if (verts [i].position.y < repairY) //repairY = verts [k+ 3]
或者是拿对应的点进行判断

**Comment by youZhuang** [comment]
尝试了楼上的方法有些字变歪了
最后调试发现
if (verts [i].position.y < repairY) {// to judge current char in the same line or not
换成
if (verts [i+2].position.y < repairY) {// to judge current char in the same line or not
这样是对的
