### ISSUE TITLE
android上无法显示表情

### ISSUE THREAD

**Issue by zhangxinlei-cn** [zouchunyi/EmojiText#5]
下载的工程在编辑器模式下运行显示正常，打包安装在安卓手机上后无法显示表情，请问这是什么原因？
![i98v0iahbjh6f5 ues1 cg](https://cloud.githubusercontent.com/assets/26061383/24573076/4a4e624a-16b1-11e7-8ebb-b48063b68eda.png)

**Comment by Zaxle-C** [comment]
>
