### ISSUE TITLE
BUG与建议

### ISSUE THREAD

**Issue by afeilo** [zouchunyi/EmojiText#8]
换行的时候有BUG，现在是根据偏移量做减法，我觉得在正则表达式匹配完成后可以直接将对应的占位符用一个特殊字符替换掉。之后再调用
		var settings = GetGenerationSettings(extents);
		cachedTextGenerator.Populate(emojitext, settings);
计算出坐标，最后在设置需要显示表情位置顶点的UV即可，可省略计算偏移

**Comment by youZhuang** [comment]
赞同，现在算mesh是会把俩中括号给算进去了。。。

**Comment by dongyiqi** [comment]
非常同意你的看法，原来的方案[1][1A]会导致计算文本宽度，换行都有问题。
换成如下的代码效果会好很多~
string strEmojiText = null;
		if (supportRichText) {
			//[1] [123] 替换成#的下标偏移量
			int nOffset = 0;
			MatchCollection matches = Regex.Matches (text, "\\[[a-z0-9A-Z]+\\]");
			for (int i = 0; i < matches.Count; i++) {
				EmojiInfo info;
				if (EmojiIndex.TryGetValue (matches [i].Value, out info)) {
					info.len = matches [i].Length;
                    emojiDic.Add(matches[i].Index - nOffset, info);
                    nOffset += info.len - 1;
				}
			}
			strEmojiText = Regex.Replace(text, "\\[[a-z0-9A-Z]+\\]", "%");
		}

		// We don't care if we the font Texture changes while we are doing our Update.
		// The end result of cachedTextGenerator will be valid for this instance.
		// Otherwise we can get issues like Case 619238.
		m_DisableFontTextureRebuiltCallback = true;

		Vector2 extents = rectTransform.rect.size;

		var settings = GetGenerationSettings(extents);
		cachedTextGenerator.Populate(strEmojiText, settings);
